export type PackKind = 'success' | 'memory'

export type Pack = {
  slug: string
  title: string
  kind: PackKind
  category: string
  image: string
  accent: string
  summary: string
  bestFor: string
  outcomes: string[]
  workflows: string[]
  recommendedMemory?: string[]
  pairsWith?: string[]
}

export const memoryPacks: Pack[] = [
  {
    slug: "founder-identity-and-voice",
    title: "Founder Identity & Voice Memory Pack",
    kind: "memory",
    category: "Founder & Personal Mastery",
    image: "/lux-agent-website/packs/memory-official/MP001_founder_identity_and_voice.png",
    accent: "#38bdf8",
    summary: "Helps LANA understand the founder's mission, tone, standards, and personal operating style.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra founder & personal mastery knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Founder Identity & Voice Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Founder Identity & Voice to improve my next move without changing my active Success Pack.","use Founder Identity & Voice to improve my offer or follow-up.","use Founder Identity & Voice to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "daily-discipline-os",
    title: "Daily Discipline OS Memory Pack",
    kind: "memory",
    category: "Founder & Personal Mastery",
    image: "/lux-agent-website/packs/memory-official/MP002_daily_discipline_os.png",
    accent: "#fb7185",
    summary: "Adds discipline, consistency, and daily execution habits to every active Success Pack.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra founder & personal mastery knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Daily Discipline OS Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Daily Discipline OS to improve my next move without changing my active Success Pack.","use Daily Discipline OS to improve my offer or follow-up.","use Daily Discipline OS to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "confidence-builder",
    title: "Confidence Builder Memory Pack",
    kind: "memory",
    category: "Founder & Personal Mastery",
    image: "/lux-agent-website/packs/memory-official/MP003_confidence_builder.png",
    accent: "#2dd4bf",
    summary: "Strengthens decision confidence, sales confidence, and public-facing founder presence.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra founder & personal mastery knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Confidence Builder Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Confidence Builder to improve my next move without changing my active Success Pack.","use Confidence Builder to improve my offer or follow-up.","use Confidence Builder to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "negotiation-street-smarts",
    title: "Negotiation Street Smarts Memory Pack",
    kind: "memory",
    category: "Founder & Personal Mastery",
    image: "/lux-agent-website/packs/memory-official/MP004_negotiation_street_smarts.png",
    accent: "#fbbf24",
    summary: "Teaches the team how to bargain, protect value, and avoid weak deals.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra founder & personal mastery knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Negotiation Street Smarts Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Negotiation Street Smarts to improve my next move without changing my active Success Pack.","use Negotiation Street Smarts to improve my offer or follow-up.","use Negotiation Street Smarts to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "public-speaking-and-pitching",
    title: "Public Speaking & Pitching Memory Pack",
    kind: "memory",
    category: "Founder & Personal Mastery",
    image: "/lux-agent-website/packs/memory-official/MP005_public_speaking_and_pitching.png",
    accent: "#f472b6",
    summary: "Improves pitches, intros, presentations, and camera-ready speaking.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra founder & personal mastery knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Public Speaking & Pitching Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Public Speaking & Pitching to improve my next move without changing my active Success Pack.","use Public Speaking & Pitching to improve my offer or follow-up.","use Public Speaking & Pitching to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "emotional-resilience",
    title: "Emotional Resilience Memory Pack",
    kind: "memory",
    category: "Founder & Personal Mastery",
    image: "/lux-agent-website/packs/memory-official/MP006_emotional_resilience.png",
    accent: "#f0abfc",
    summary: "Helps the team coach the user through pressure, setbacks, and launch stress.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra founder & personal mastery knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Emotional Resilience Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Emotional Resilience to improve my next move without changing my active Success Pack.","use Emotional Resilience to improve my offer or follow-up.","use Emotional Resilience to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "leadership-presence",
    title: "Leadership Presence Memory Pack",
    kind: "memory",
    category: "Founder & Personal Mastery",
    image: "/lux-agent-website/packs/memory-official/MP007_leadership_presence.png",
    accent: "#34d399",
    summary: "Adds CEO-style leadership language, delegation, and team accountability.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra founder & personal mastery knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Leadership Presence Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Leadership Presence to improve my next move without changing my active Success Pack.","use Leadership Presence to improve my offer or follow-up.","use Leadership Presence to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "time-blocking-and-focus",
    title: "Time Blocking & Focus Memory Pack",
    kind: "memory",
    category: "Founder & Personal Mastery",
    image: "/lux-agent-website/packs/memory-official/MP008_time_blocking_and_focus.png",
    accent: "#60a5fa",
    summary: "Improves daily planning, sprint structure, and protection from distractions.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra founder & personal mastery knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Time Blocking & Focus Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Time Blocking & Focus to improve my next move without changing my active Success Pack.","use Time Blocking & Focus to improve my offer or follow-up.","use Time Blocking & Focus to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "decision-maker-framework",
    title: "Decision Maker Framework Memory Pack",
    kind: "memory",
    category: "Founder & Personal Mastery",
    image: "/lux-agent-website/packs/memory-official/MP009_decision_maker_framework.png",
    accent: "#a275ff",
    summary: "Helps LANA simplify complex choices into clean options and next moves.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra founder & personal mastery knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Decision Maker Framework Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Decision Maker Framework to improve my next move without changing my active Success Pack.","use Decision Maker Framework to improve my offer or follow-up.","use Decision Maker Framework to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "faith-purpose-and-values",
    title: "Faith, Purpose & Values Memory Pack",
    kind: "memory",
    category: "Founder & Personal Mastery",
    image: "/lux-agent-website/packs/memory-official/MP010_faith_purpose_and_values.png",
    accent: "#c084fc",
    summary: "Adds values-first thinking, service, integrity, and spiritual grounding.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra founder & personal mastery knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Faith, Purpose & Values Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Faith, Purpose & Values to improve my next move without changing my active Success Pack.","use Faith, Purpose & Values to improve my offer or follow-up.","use Faith, Purpose & Values to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "consultative-selling",
    title: "Consultative Selling Memory Pack",
    kind: "memory",
    category: "Sales & Revenue",
    image: "/lux-agent-website/packs/memory-official/MP011_consultative_selling.png",
    accent: "#22d3ee",
    summary: "Improves discovery calls, needs analysis, and customer-centered sales.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra sales & revenue knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Consultative Selling Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Consultative Selling to improve my next move without changing my active Success Pack.","use Consultative Selling to improve my offer or follow-up.","use Consultative Selling to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "cold-outreach-that-feels-human",
    title: "Cold Outreach That Feels Human Memory Pack",
    kind: "memory",
    category: "Sales & Revenue",
    image: "/lux-agent-website/packs/memory-official/MP012_cold_outreach_that_feels_human.png",
    accent: "#f97316",
    summary: "Helps Dre write DMs, emails, and texts that sound real and respectful.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra sales & revenue knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Cold Outreach That Feels Human Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Cold Outreach That Feels Human to improve my next move without changing my active Success Pack.","use Cold Outreach That Feels Human to improve my offer or follow-up.","use Cold Outreach That Feels Human to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "follow-up-machine",
    title: "Follow-Up Machine Memory Pack",
    kind: "memory",
    category: "Sales & Revenue",
    image: "/lux-agent-website/packs/memory-official/MP013_follow_up_machine.png",
    accent: "#0ea5e9",
    summary: "Adds structured follow-up timing, scripts, and gentle persistence.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra sales & revenue knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Follow-Up Machine Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Follow-Up Machine to improve my next move without changing my active Success Pack.","use Follow-Up Machine to improve my offer or follow-up.","use Follow-Up Machine to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "objection-handling",
    title: "Objection Handling Memory Pack",
    kind: "memory",
    category: "Sales & Revenue",
    image: "/lux-agent-website/packs/memory-official/MP014_objection_handling.png",
    accent: "#14b8a6",
    summary: "Helps the team respond to price, timing, trust, and uncertainty objections.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra sales & revenue knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Objection Handling Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Objection Handling to improve my next move without changing my active Success Pack.","use Objection Handling to improve my offer or follow-up.","use Objection Handling to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "offer-design",
    title: "Offer Design Memory Pack",
    kind: "memory",
    category: "Sales & Revenue",
    image: "/lux-agent-website/packs/memory-official/MP015_offer_design.png",
    accent: "#f59e0b",
    summary: "Turns services into clear, valuable, easy-to-buy offers.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra sales & revenue knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Offer Design Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Offer Design to improve my next move without changing my active Success Pack.","use Offer Design to improve my offer or follow-up.","use Offer Design to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "proposal-writing",
    title: "Proposal Writing Memory Pack",
    kind: "memory",
    category: "Sales & Revenue",
    image: "/lux-agent-website/packs/memory-official/MP016_proposal_writing.png",
    accent: "#22c55e",
    summary: "Improves proposals, scopes, summaries, and close-ready client documents.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra sales & revenue knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Proposal Writing Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Proposal Writing to improve my next move without changing my active Success Pack.","use Proposal Writing to improve my offer or follow-up.","use Proposal Writing to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "pricing-psychology",
    title: "Pricing Psychology Memory Pack",
    kind: "memory",
    category: "Sales & Revenue",
    image: "/lux-agent-website/packs/memory-official/MP017_pricing_psychology.png",
    accent: "#8b5cf6",
    summary: "Helps Anna and Dre frame price around value, outcomes, and risk reduction.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra sales & revenue knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Pricing Psychology Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Pricing Psychology to improve my next move without changing my active Success Pack.","use Pricing Psychology to improve my offer or follow-up.","use Pricing Psychology to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "client-retention",
    title: "Client Retention Memory Pack",
    kind: "memory",
    category: "Sales & Revenue",
    image: "/lux-agent-website/packs/memory-official/MP018_client_retention.png",
    accent: "#06b6d4",
    summary: "Adds renewal, check-in, upsell, and loyalty systems.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra sales & revenue knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Client Retention Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Client Retention to improve my next move without changing my active Success Pack.","use Client Retention to improve my offer or follow-up.","use Client Retention to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "referral-flywheel",
    title: "Referral Flywheel Memory Pack",
    kind: "memory",
    category: "Sales & Revenue",
    image: "/lux-agent-website/packs/memory-official/MP019_referral_flywheel.png",
    accent: "#ec4899",
    summary: "Creates referral asks, partner scripts, and customer champion workflows.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra sales & revenue knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Referral Flywheel Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Referral Flywheel to improve my next move without changing my active Success Pack.","use Referral Flywheel to improve my offer or follow-up.","use Referral Flywheel to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  },
  {
    slug: "local-networking",
    title: "Local Networking Memory Pack",
    kind: "memory",
    category: "Sales & Revenue",
    image: "/lux-agent-website/packs/memory-official/MP020_local_networking.png",
    accent: "#818cf8",
    summary: "Adds community-first networking, warm introductions, and local relationship building.",
    bestFor: "Any active Lux Agent Success Pack",
    outcomes: ["Enhance the active Success Pack with extra sales & revenue knowledge.","Give the AI team more real-world context before writing, planning, or advising.","Improve task routing, draft quality, and decision support without switching industries.","Create a deeper, more human-feeling teammate perspective."],
    workflows: ["apply the Local Networking Memory Pack to my active Success Pack and tell me what changes in how the team thinks.","use Local Networking to improve my next move without changing my active Success Pack.","use Local Networking to improve my offer or follow-up.","use Local Networking to create a better campaign angle."],
    pairsWith: ["Any active Success Pack"],
  }
]

export const successPacks: Pack[] = [
  {
    slug: "real-estate",
    title: "Real Estate Success Pack",
    kind: "success",
    category: "Real Estate",
    image: "/lux-agent-website/packs/success-official/001-real-estate.png",
    accent: "#38bdf8",
    summary: "An all-in-one AI assistant playbook for real estate agent / brokers who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for real estate agent / brokers and teams that need a focused AI operating playbook.",
    outcomes: ["Lead generation","Listing optimization","Open house follow-up","Buyer/seller communication"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["consultative-selling","follow-up-machine","proposal-writing","local-networking"],
  },
  {
    slug: "restaurant",
    title: "Restaurant Success Pack",
    kind: "success",
    category: "Food & Hospitality",
    image: "/lux-agent-website/packs/success-official/002-restaurant.png",
    accent: "#fb7185",
    summary: "An all-in-one AI assistant playbook for restaurant owner / chefs who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for restaurant owner / chefs and teams that need a focused AI operating playbook.",
    outcomes: ["More customers","Smarter reviews","Better bookings","Menu and pricing"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["offer-design","public-speaking-and-pitching","referral-flywheel","local-networking"],
  },
  {
    slug: "doctor-clinic",
    title: "Doctor / Clinic Success Pack",
    kind: "success",
    category: "Healthcare Practice",
    image: "/lux-agent-website/packs/success-official/003-doctor-clinic.png",
    accent: "#2dd4bf",
    summary: "An all-in-one AI assistant playbook for clinic owner / doctors who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for clinic owner / doctors and teams that need a focused AI operating playbook.",
    outcomes: ["Patient booking","Follow-up care","Chart notes","Reputation and reviews"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["client-retention","consultative-selling","follow-up-machine","local-networking"],
  },
  {
    slug: "electrical-contractor",
    title: "Electrical Contractor Success Pack",
    kind: "success",
    category: "Trades",
    image: "/lux-agent-website/packs/success-official/004-electrical-contractor.png",
    accent: "#fbbf24",
    summary: "An all-in-one AI assistant playbook for electrical contractors who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for electrical contractors and teams that need a focused AI operating playbook.",
    outcomes: ["More jobs","Quotes and estimates","Scheduling","Invoicing and payments"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["cold-outreach-that-feels-human","follow-up-machine","objection-handling","pricing-psychology"],
  },
  {
    slug: "creator",
    title: "Creator Success Pack",
    kind: "success",
    category: "Creator Economy",
    image: "/lux-agent-website/packs/success-official/005-creator.png",
    accent: "#f472b6",
    summary: "An all-in-one AI assistant playbook for content creators who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for content creators and teams that need a focused AI operating playbook.",
    outcomes: ["Content ideas","Script writing","Captions and hooks","Scheduling"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["offer-design","public-speaking-and-pitching","referral-flywheel","local-networking"],
  },
  {
    slug: "beauty-salon",
    title: "Beauty / Salon Success Pack",
    kind: "success",
    category: "Beauty & Wellness",
    image: "/lux-agent-website/packs/success-official/006-beauty-salon.png",
    accent: "#f0abfc",
    summary: "An all-in-one AI assistant playbook for salon owner / stylists who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for salon owner / stylists and teams that need a focused AI operating playbook.",
    outcomes: ["Appointment booking","Client reminders","Social media content","Reviews and reputation"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["offer-design","public-speaking-and-pitching","referral-flywheel","local-networking"],
  },
  {
    slug: "fitness-coach",
    title: "Fitness Coach Success Pack",
    kind: "success",
    category: "Fitness",
    image: "/lux-agent-website/packs/success-official/007-fitness-coach.png",
    accent: "#34d399",
    summary: "An all-in-one AI assistant playbook for fitness coachs who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for fitness coachs and teams that need a focused AI operating playbook.",
    outcomes: ["Client acquisition","Workout programs","Nutrition guidance","Check-ins and follow-up"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["client-retention","consultative-selling","follow-up-machine","local-networking"],
  },
  {
    slug: "realtor-team",
    title: "Realtor Team Success Pack",
    kind: "success",
    category: "Real Estate Teams",
    image: "/lux-agent-website/packs/success-official/008-realtor-team.png",
    accent: "#60a5fa",
    summary: "An all-in-one AI assistant playbook for realtor team leaders who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for realtor team leaders and teams that need a focused AI operating playbook.",
    outcomes: ["Team lead generation","Listing management","Marketing systems","Buyer/seller care"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["consultative-selling","follow-up-machine","proposal-writing","local-networking"],
  },
  {
    slug: "insurance-agent",
    title: "Insurance Agent Success Pack",
    kind: "success",
    category: "Insurance",
    image: "/lux-agent-website/packs/success-official/009-insurance-agent.png",
    accent: "#a275ff",
    summary: "An all-in-one AI assistant playbook for insurance agents who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for insurance agents and teams that need a focused AI operating playbook.",
    outcomes: ["Lead generation","Policy follow-up","Client communication","Renewals and reminders"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["consultative-selling","follow-up-machine","proposal-writing","local-networking"],
  },
  {
    slug: "consultant",
    title: "Consultant Success Pack",
    kind: "success",
    category: "Professional Services",
    image: "/lux-agent-website/packs/success-official/010-consultant.png",
    accent: "#c084fc",
    summary: "An all-in-one AI assistant playbook for business consultants who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for business consultants and teams that need a focused AI operating playbook.",
    outcomes: ["Client acquisition","Proposals and offers","Project management","Reports and analysis"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["consultative-selling","follow-up-machine","proposal-writing","local-networking"],
  },
  {
    slug: "barbershop",
    title: "Barbershop Success Pack",
    kind: "success",
    category: "Beauty & Grooming",
    image: "/lux-agent-website/packs/success-official/011-barbershop.png",
    accent: "#22d3ee",
    summary: "An all-in-one AI assistant playbook for barbershop owners who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for barbershop owners and teams that need a focused AI operating playbook.",
    outcomes: ["Bookings","Client retention","Review growth","Social reels"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["offer-design","public-speaking-and-pitching","referral-flywheel","local-networking"],
  },
  {
    slug: "auto-repair",
    title: "Auto Repair Success Pack",
    kind: "success",
    category: "Automotive",
    image: "/lux-agent-website/packs/success-official/012-auto-repair.png",
    accent: "#f97316",
    summary: "An all-in-one AI assistant playbook for auto shop owners who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for auto shop owners and teams that need a focused AI operating playbook.",
    outcomes: ["Appointments","Estimates","Parts tracking","Reviews"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["cold-outreach-that-feels-human","follow-up-machine","objection-handling","pricing-psychology"],
  },
  {
    slug: "hvac",
    title: "HVAC Contractor Success Pack",
    kind: "success",
    category: "Trades",
    image: "/lux-agent-website/packs/success-official/013-hvac.png",
    accent: "#0ea5e9",
    summary: "An all-in-one AI assistant playbook for HVAC contractors who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for HVAC contractors and teams that need a focused AI operating playbook.",
    outcomes: ["Quotes","Scheduling","Maintenance plans","Seasonal campaigns"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["cold-outreach-that-feels-human","follow-up-machine","objection-handling","pricing-psychology"],
  },
  {
    slug: "plumbing",
    title: "Plumbing Contractor Success Pack",
    kind: "success",
    category: "Trades",
    image: "/lux-agent-website/packs/success-official/014-plumbing.png",
    accent: "#14b8a6",
    summary: "An all-in-one AI assistant playbook for plumbers who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for plumbers and teams that need a focused AI operating playbook.",
    outcomes: ["Emergency leads","Estimates","Recurring maintenance","Invoices"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["cold-outreach-that-feels-human","follow-up-machine","objection-handling","pricing-psychology"],
  },
  {
    slug: "roofing",
    title: "Roofing Contractor Success Pack",
    kind: "success",
    category: "Trades",
    image: "/lux-agent-website/packs/success-official/015-roofing.png",
    accent: "#f59e0b",
    summary: "An all-in-one AI assistant playbook for roofing contractors who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for roofing contractors and teams that need a focused AI operating playbook.",
    outcomes: ["Inspection leads","Estimates","Crew scheduling","Insurance support notes"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["cold-outreach-that-feels-human","follow-up-machine","objection-handling","pricing-psychology"],
  },
  {
    slug: "landscaping",
    title: "Landscaping Success Pack",
    kind: "success",
    category: "Home Services",
    image: "/lux-agent-website/packs/success-official/016-landscaping.png",
    accent: "#22c55e",
    summary: "An all-in-one AI assistant playbook for landscaping owners who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for landscaping owners and teams that need a focused AI operating playbook.",
    outcomes: ["Seasonal packages","Route planning","Before/after content","Recurring clients"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["cold-outreach-that-feels-human","follow-up-machine","objection-handling","pricing-psychology"],
  },
  {
    slug: "cleaning-service",
    title: "Cleaning Service Success Pack",
    kind: "success",
    category: "Home Services",
    image: "/lux-agent-website/packs/success-official/017-cleaning-service.png",
    accent: "#8b5cf6",
    summary: "An all-in-one AI assistant playbook for cleaning business owners who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for cleaning business owners and teams that need a focused AI operating playbook.",
    outcomes: ["Recurring contracts","Checklists","Quotes","Client reminders"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["cold-outreach-that-feels-human","follow-up-machine","objection-handling","pricing-psychology"],
  },
  {
    slug: "mobile-detailing",
    title: "Mobile Detailing Success Pack",
    kind: "success",
    category: "Automotive",
    image: "/lux-agent-website/packs/success-official/018-mobile-detailing.png",
    accent: "#06b6d4",
    summary: "An all-in-one AI assistant playbook for mobile detailers who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for mobile detailers and teams that need a focused AI operating playbook.",
    outcomes: ["Booking routes","Package upsells","Photo proof","Reviews"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["cold-outreach-that-feels-human","follow-up-machine","objection-handling","pricing-psychology"],
  },
  {
    slug: "event-planner",
    title: "Event Planner Success Pack",
    kind: "success",
    category: "Events",
    image: "/lux-agent-website/packs/success-official/019-event-planner.png",
    accent: "#ec4899",
    summary: "An all-in-one AI assistant playbook for event planners who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for event planners and teams that need a focused AI operating playbook.",
    outcomes: ["Leads","Proposals","Vendor timelines","Client checklists"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["offer-design","public-speaking-and-pitching","referral-flywheel","local-networking"],
  },
  {
    slug: "photographer",
    title: "Photographer Success Pack",
    kind: "success",
    category: "Creative Services",
    image: "/lux-agent-website/packs/success-official/020-photographer.png",
    accent: "#818cf8",
    summary: "An all-in-one AI assistant playbook for photographers who want better systems, stronger content, cleaner follow-up, and more organized growth.",
    bestFor: "Built for photographers and teams that need a focused AI operating playbook.",
    outcomes: ["Bookings","Shot lists","Packages","Galleries"],
    workflows: ["Complete Business HQ so LANA knows the business.","Activate the Success Pack in Success Packs.","Copy First Chat into Ask LANA.","Let LANA route work to the correct teammate."],
    recommendedMemory: ["offer-design","public-speaking-and-pitching","referral-flywheel","local-networking"],
  }
]

export const getSuccessPack = (slug: string) => successPacks.find(pack => pack.slug === slug)
export const getMemoryPack = (slug: string) => memoryPacks.find(pack => pack.slug === slug)

export const memoryBySlug = new Map(memoryPacks.map(pack => [pack.slug, pack]))
